#!/usr/bin/env bash
# Generates vendor/gpui-pre-windows/precompiled/shaders_bytes.rs:
# the GPUI HLSL shaders compiled with the Windows SDK's fxc.exe running under
# Wine. This lets the Windows desktop app be built from Linux or macOS (see
# vendor/gpui-pre-windows/README.md).
#
# Only needed when updating gpui-pre. Requires wine, curl, unzip and python3.
# The SDK (NuGet package Microsoft.Windows.SDK.CPP, ~160 MB) is downloaded
# once into ~/.cache/termoak/fxc; FXC_DIR can point to a folder that already
# has fxc.exe and d3dcompiler_47.dll.
#
# Usage: scripts/gen-windows-shaders.sh
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
crate="$root/vendor/gpui-pre-windows"
version="$(sed -n 's/^version = "\(.*\)"/\1/p' "$crate/Cargo.toml" | head -1)"
sdk_version="10.0.28000.2705"

for tool in wine curl unzip python3; do
  command -v "$tool" >/dev/null || { echo "$tool is missing" >&2; exit 1; }
done

fxc_dir="${FXC_DIR:-$HOME/.cache/termoak/fxc}"
if [[ ! -f "$fxc_dir/fxc.exe" ]]; then
  echo "Downloading fxc.exe from Windows SDK $sdk_version…"
  mkdir -p "$fxc_dir"
  pkg="$(mktemp)"
  curl -fsSL -o "$pkg" \
    "https://api.nuget.org/v3-flatcontainer/microsoft.windows.sdk.cpp/$sdk_version/microsoft.windows.sdk.cpp.$sdk_version.nupkg"
  unzip -o -q -j "$pkg" \
    "c/bin/${sdk_version%.*}.0/x64/fxc.exe" \
    "c/bin/${sdk_version%.*}.0/x64/d3dcompiler_47.dll" -d "$fxc_dir"
  rm -f "$pkg"
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
cp "$crate"/src/*.hlsl "$fxc_dir/fxc.exe" "$fxc_dir/d3dcompiler_47.dll" "$work/"
export WINEPREFIX="${WINEPREFIX:-$HOME/.cache/termoak/wine}" WINEDEBUG=-all

# Same modules, entry points and options as the original build.rs.
compile() { # module file
  local module="$1" file="$2"
  for kind in vertex:vs_4_1:VERTEX fragment:ps_4_1:FRAGMENT; do
    IFS=: read -r entry target suffix <<<"$kind"
    local name
    name="$(printf %s "$module" | tr "[:lower:]" "[:upper:]")_${suffix}_BYTES"
    (cd "$work" && wine fxc.exe /nologo /T "$target" /E "${module}_${entry}" \
      /Fh "${module}_${entry}.h" /Vn "$name" /O3 "$file" >/dev/null)
  done
}
for m in quad shadow path_rasterization path_sprite underline monochrome_sprite \
  subpixel_sprite polychrome_sprite; do
  compile "$m" shaders.hlsl
done
compile emoji_rasterization color_text_raster.hlsl

mkdir -p "$crate/precompiled"
python3 - "$work" "$crate/precompiled/shaders_bytes.rs" "$version" "$sdk_version" <<'EOF'
import pathlib, re, sys
work, out, version, sdk = sys.argv[1:]
modules = ["quad", "shadow", "path_rasterization", "path_sprite", "underline",
           "monochrome_sprite", "subpixel_sprite", "polychrome_sprite", "emoji_rasterization"]
lines = [
    "// Generated by scripts/gen-windows-shaders.sh: do not edit by hand.",
    f"// gpui-pre-windows {version} shaders compiled with fxc.exe (Windows SDK {sdk}).",
]
for m in modules:
    for entry, suffix in (("vertex", "VERTEX"), ("fragment", "FRAGMENT")):
        text = (pathlib.Path(work) / f"{m}_{entry}.h").read_text(errors="replace")
        body = text[text.index("const BYTE"):]
        values = re.findall(r"\d+", body[body.index("{"):body.index("}")])
        data = bytes(int(v) for v in values)
        assert data[:4] == b"DXBC", f"{m}_{entry}: not DXBC bytecode"
        rows = [", ".join(str(b) for b in data[i:i + 20]) for i in range(0, len(data), 20)]
        lines.append(f"const {m.upper()}_{suffix}_BYTES: &[u8] = &[")
        lines.extend(f"    {r}," for r in rows)
        lines.append("];")
pathlib.Path(out).write_text("\n".join(lines) + "\n")
print(f"{out}: {len(modules) * 2} shaders")
EOF
